### ISSUE TITLE
Python access to samples?

### ISSUE THREAD

**Issue by akloster** [neXyon/audaspace#1] opened 2015-05-26 03:16 UTC
I have been glancing at the code, and I am not quite sure if there is a possibility to get the actual audio samples from the audaspace API.

My particular usecase is that I would like to make a plugin for blender's sequencer which can synchronize audio strips. However, I could not find a solution to retrieve the audio samples in a way that is platform agnostic enough. The best I came up with was trying to use libraries and programs not in the standard blender distribution.

Which is a bit awkward, because blender can obviously access the samples, like when the waveforms are drawn or when sound is baked to an fcurve. The former happens (to my knowledge) completely outside the Python bindings, and the sound baking operator has various limitations, for example I need to create an fcurve somewhere, delete it afterwards and hope I didn't mess anything else up.

Anyway, what would be great is some property like "Image.pixels", which results in a float array.

Most Ideal would be an interface to numpy (which is included in Blender), either by copying the data directly, or using a memory view. That would make sound analysis through numpy and scipy means a lot easier.

**Comment by neXyon** [comment] 2015-05-27 09:35
This is on my todo list for the library, but I first have to get this version of the library here into blender, which I will be able to do soon hopefully, but it will probably take two or three more releases until this is in blender. If it's urgent I recommend to use another library meanwhile.

**Comment by akloster** [comment] 2015-05-27 11:20
No haste! I just wanted to express why someone would be interested in such a feature.

I'm also looking forward to someone taking the time to implement a node-based synthesizer for Blender ;-)

**Comment by neXyon** [comment] 2015-12-24 14:44
Hey, I totally forgot to close this issue. It has been implemented with Audaspace 1.1! Cheers

**Closed by neXyon** 2015-12-24 14:44 UTC
Labels: enhancement

**Comment by JacquesLucke** [comment] 2017-02-10 12:16
Hey, I'm currently trying to find out how to improve the sound capabilities of Animation Nodes.
It can currently do things like this: https://www.youtube.com/watch?v=D-y8REUdg6I

However the problem is that the baking process is quite slow and inefficient. Especially when I have to bake multiple frequency ranges using the "bake sound to fcurve" operator.

I was wondering if I can improve this somehow, but for that I need the sound samples as well. You wrote here that it is implemented already. Can you maybe give me a short example on how I can access these samples?
The best thing would be if I could just get the samples of a blender [sound object](https://docs.blender.org/api/blender_python_api_2_78_0/bpy.types.Sound.html) in an array like object.

It would be even better if I could specify a start and end sample index. This way I would be able to handle larger files as well. But this is only a bonus. 

Thanks for your work on this project :)

**Comment by neXyon** [comment] 2017-02-10 13:36
Hi Jacques, nice work there on the sound animation nodes. As this version of audaspace is not used in the official builds of blender yet, you cannot use it straight away, you would have to build blender with this library yourself. The plan is to change this with blender 2.8, but no idea when this will come out and is usable for the end users. Before that it's probably not advisable to use the functionality from this audaspace version, yet?

The processing that is done on the audio samples to get the f-curve animation is not 100 % trivial either, so if you do it for the whole audio file, you won't be able to do it much faster than it is currently. I guess what you want to do is doing it realtime for the part that you are animating right now?

**Comment by JacquesLucke** [comment] 2017-02-10 19:37
ok, then I will postbone this development until your newest work is in blender. I totally understand that you won't be able to merge it earlier.

Is it possible to get an api function like this into Blender? (I don't know how your current api looks like)
`
bpy.data.sounds["sound name"].get_samples(int start, int end) -> array
`
The array should be either a numpy array or an python [array](https://docs.python.org/3/library/array.html). Obviously it should not be a normal python list for because of too much memory usage. Also I could process the data much faster in real arrays. Not only could I use all the numpy functionality but I can also write Cython code that handles all that data as fast as C code.

I'm already quite happy that there is this Bake Sound to FCurve operator but there are a lot of downsides in using it in addons like Animation Nodes.  Mostly because I always need workarounds to use it. It highly depends on the scene state (active object, ...). A more low level function would be helpful and also faster because often there is no need to create a fcurve.

Also note that I don't know too much about audio in general atm (but I'm a quick learner). I just learned about FFT a few weeks ago in university and did some experiments today in Blender. It worked out quite well. The main problem is that I cannot easily load different types of audio formats and access their samples.

![fft test](https://cloud.githubusercontent.com/assets/5881326/22841051/4336660e-efd0-11e6-838b-580994ad498c.PNG)

I see that the bake sound to fcurve operator does some things that can't really be done efficiently in realtime when the user can jump between frames because everything depends on everything before. However in many cases I don't need that behaviour. It just gives me much more flexibility when I can calculate the exact data I need for a specific purpose.

**Comment by neXyon** [comment] 2017-02-21 10:32
Hi,

as for the API, it is already mostly accessible: bpy.data.sounds[str name].factory.limit(float start, float stop).data()
except for the last step [data](http://audaspace.github.io/bindings/sound.html#aud.Sound.data) you can do everything in the current Blender version already.

The start and end time are seconds however, not samples, it should be accurate enough though. The result is a numpy array. You can do this with any Sound (was previously called Factory) object of audaspace, bpy.data.sounds[x].factory is only one way to get such a Sound object and it is lightweight. Reading the file isn't however... It's better if the sound is cached (if the bpy sound is cached it's factory is the cached version, otherwise you can cache yourself with cache() - this loads the whole sound into RAM).

Regarding the parts that depend on previous samples in the baking operator: it should be safe to load a few samples before the actual start of the range that you are interested in and get pretty much the same result as processing the whole file.

**Comment by JacquesLucke** [comment] 2017-02-21 22:47
hey that looks pretty cool, thank your for that information. I'm very happy that you already implemented everything I need ;D This will make it much more likely that it will eventually be in Blender. I'm looking forward to that. Thanks again!

**Comment by JacquesLucke** [comment] 2019-01-15 12:03
@neXyon, it's so cool what possibilities such a small function can open up: https://twitter.com/OmarSquircleArt/status/1084881010234404864

**Comment by neXyon** [comment] 2019-01-17 20:33
Thanks for sharing, love to see this stuff!
